# Generated by Django 4.2 on 2023-04-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
                ('class_image', models.ImageField(blank=True, upload_to='classes/')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('faction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('faction_name', models.CharField(max_length=255)),
                ('faction_image', models.ImageField(blank=True, upload_to='factions/')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('rarity_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rarity_name', models.CharField(max_length=255)),
                ('rarity_image', models.ImageField(blank=True, upload_to='rarity/')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('skill_type_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('skill_type_name', models.CharField(max_length=255)),
                ('skill_type_image', models.ImageField(blank=True, upload_to='skill_types/')),
            ],
        ),
        migrations.CreateModel(
            name='SpanType',
            fields=[
                ('span_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('span_name', models.CharField(max_length=255)),
                ('span_image', models.ImageField(blank=True, upload_to='span_types/')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=255)),
                ('skill_image', models.ImageField(blank=True, upload_to='skills/')),
                ('skill_cost', models.IntegerField(blank=True)),
                ('skill_cd', models.IntegerField(blank=True)),
                ('skill_range', models.IntegerField(blank=True)),
                ('skill_span', models.IntegerField(blank=True)),
                ('skill', models.TextField(blank=True)),
                ('span_type', models.ManyToManyField(blank=True, related_name='skills', to='heroes.spantype')),
                ('type', models.ManyToManyField(blank=True, related_name='skills', to='heroes.skilltype')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hero_name', models.CharField(blank=True, max_length=255)),
                ('hero_icon', models.ImageField(blank=True, upload_to='hero_icons/')),
                ('hero_image', models.ImageField(blank=True, upload_to='hero_images/')),
                ('talent_name', models.CharField(blank=True, max_length=255)),
                ('talent_image', models.ImageField(blank=True, upload_to='talents/')),
                ('talent', models.TextField(blank=True)),
                ('sp_talent_name', models.CharField(blank=True, max_length=255)),
                ('sp_talent_image', models.ImageField(blank=True, upload_to='sp_talents/')),
                ('sp_talent', models.TextField(blank=True)),
                ('class_1_name', models.CharField(blank=True, max_length=255)),
                ('class_1_stats', models.TextField(blank=True)),
                ('class_2_name', models.CharField(blank=True, max_length=255)),
                ('class_2_stats', models.TextField(blank=True)),
                ('class_3_name', models.CharField(blank=True, max_length=255)),
                ('class_3_stats', models.TextField(blank=True)),
                ('exclusive_name', models.CharField(blank=True, max_length=255)),
                ('exclusive_image', models.ImageField(blank=True, upload_to='exclusive_equipment/')),
                ('exclusive', models.TextField(blank=True)),
                ('casting_pattern_name', models.CharField(blank=True, max_length=255)),
                ('casting_pattern_image', models.ImageField(blank=True, upload_to='casting_patterns/')),
                ('casting_pattern', models.TextField(blank=True)),
                ('bonds_lock', models.ManyToManyField(blank=True, related_name='bond_unlock', to='heroes.hero')),
                ('classes', models.ManyToManyField(blank=True, related_name='heroes', to='heroes.class')),
                ('factions', models.ManyToManyField(blank=True, related_name='heroes', to='heroes.faction')),
                ('rarity', models.ManyToManyField(blank=True, related_name='heroes', to='heroes.rarity')),
                ('skills', models.ManyToManyField(blank=True, related_name='heroes', to='heroes.skill')),
            ],
        ),
    ]
